import { Inter } from 'next/font/google'
import './globals.css'
import Footer from '@/components/Footer/page'
import { ClerkProvider } from '@clerk/nextjs'
import NavBar from '@/components/Navbar/page'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'StaffSync',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
        <main className='container mx-auto'>
          <div className="d-flex justify-center items-center min-h-screen">
            <NavBar />
            {children}
            <Footer />
          </div>
          </main>
        </body>
      </html>
    </ClerkProvider>
  )
}
