import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar/page'
import './globals.css'
import Footer from '@/components/Footer/page'
import { ClerkProvider } from '@clerk/nextjs'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'StaffSync',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <div className="d-flex justify-center items-center">
            <Navbar />
            {children}
            <Footer />
          </div>
        </body>
      </html>
    </ClerkProvider>
  )
}
